// data.js

export const employeeData = [
  {
    id: "EMP001",
    name: "Sarah Johnson",
    email: "sarah.johnson@company.com",
    role: "Senior Developer",
    department: "Engineering",
    joinDate: "15 Jan 2022",
    status: "Aktif",
    avatar: "https://i.pravatar.cc/150?u=EMP001", // Placeholder image
  },
  {
    id: "EMP002",
    name: "Michael Chen",
    email: "michael.chen@company.com",
    role: "Product Designer",
    department: "Design",
    joinDate: "20 Jun 2021",
    status: "Aktif",
    avatar: "https://i.pravatar.cc/150?u=EMP002",
  },
  {
    id: "EMP003",
    name: "Emily Rodriguez",
    email: "emily.rodriguez@company.com",
    role: "Marketing Manager",
    department: "Marketing",
    joinDate: "10 Nov 2020",
    status: "Cuti",
    avatar: "https://i.pravatar.cc/150?u=EMP003",
  },
  {
    id: "EMP004",
    name: "David Kim",
    email: "david.kim@company.com",
    role: "DevOps Engineer",
    department: "Engineering",
    joinDate: "5 Mar 2021",
    status: "Tidak Aktif",
    avatar: "https://i.pravatar.cc/150?u=EMP004",
  },
  {
    id: "EMP005",
    name: "Jessica Williams",
    email: "jessica.williams@company.com",
    role: "Sales Director",
    department: "Sales",
    joinDate: "22 Aug 2019",
    status: "Aktif",
    avatar: "https://i.pravatar.cc/150?u=EMP005",
  },
  {
    id: "EMP006",
    name: "Robert Taylor",
    email: "robert.taylor@company.com",
    role: "Frontend Developer",
    department: "Engineering",
    joinDate: "18 Apr 2022",
    status: "Aktif",
    avatar: "https://i.pravatar.cc/150?u=EMP006",
  },
  {
    id: "EMP007",
    name: "Amanda Lee",
    email: "amanda.lee@company.com",
    role: "HR Specialist",
    department: "HR",
    joinDate: "30 Sep 2021",
    status: "Aktif",
    avatar: "https://i.pravatar.cc/150?u=EMP007",
  },
  {
    id: "EMP008",
    name: "Christopher Davis",
    email: "christopher.davis@company.com",
    role: "Financial Analyst",
    department: "Finance",
    joinDate: "14 Feb 2020",
    status: "Aktif",
    avatar: "https://i.pravatar.cc/150?u=EMP008",
  },
];